<div class="deco-menu-wrapper">
    <div class="deco-menu">
        <div>
            <div class="btn-menu" >
                Categorias
            </div>
            <div>
                <?= $block->getListTypeCategoryCollection() ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        'deco_menu'
    ], function (decoMenu) {
        decoMenu.menuHeight();
    });
</script>

