<div class="deco-menu-wrapper hidden-print">
    <div class="deco-menu">
        <div>
            <div class="btn-menu" >
                Categorias
            </div>
            <div>
                <?= $block->getListTypeCategoryCollection() ?>
            </div>
        </div>
    </div>
</div>

<?php $scriptString = <<<script
    require([
        'deco_menu'
    ], function (decoMenu) {
        decoMenu.menuHeight();
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>