<?php 
$categories = $block->getActiveCategoryCollection();

function childrenList(){
    
}

echo "<ul>";
foreach($categories as $category){
    if(empty($category->getChildren()) && $category->getLevel() == 2){
        echo "<ul>";
            echo "<li>";
                echo $category->getName();
            echo "</li>";
        echo "</ul>";
    }elseif(!empty($category->getChildren()) && $category->getLevel() == 2){
        echo "<ul>";
            echo "<li>";
                echo $category->getName();
            echo "</li>";
            echo "<ul>";
                foreach($categories as $categoryLevel3){
                    if(empty($categoryLevel3->getChildren()) && $categoryLevel3->getLevel() == 3 && $categoryLevel3->getParentId() == $category->getId()){
                        echo "<ul>";
                            echo "<li>";
                                echo $categoryLevel3->getName();
                            echo "</li>";
                        echo "</ul>";
                    }elseif(!empty($categoryLevel3->getChildren()) && $categoryLevel3->getLevel() == 3 && $categoryLevel3->getParentId() == $category->getId()){
                        echo "<ul>";
                            echo "<li>";
                                echo $categoryLevel3->getName();
                            echo "</li>";
                            echo "<ul>";
                                foreach($categories as $categoryLevel4){
                                    if(empty($categoryLevel4->getChildren()) && $categoryLevel4->getLevel() == 4 && $categoryLevel4->getParentId() == $categoryLevel3->getId()){
                                        echo "<ul>";
                                            echo "<li>";
                                                echo $categoryLevel4->getName();
                                            echo "</li>";
                                        echo "</ul>";
                                    }elseif(!empty($category->getChildren()) && $category->getLevel() == 4){

                                    }
                                }
                            echo "</ul>";
                        echo "</ul>";
                    }
                }
            echo "</ul>";
        echo "</ul>";
    }
}
echo "</ul>";

?>
</ul>